frontend:
  - changed-files:
      - any-glob-to-any-file:
          - 'client/**/*'

backend:
  - changed-files:
      - any-glob-to-any-file:
          - 'server/**/*'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'

bug:
  - head-branch:
      - 'fix/**'
      - 'bug/**'

enhancement:
  - head-branch:
      - 'feature/**'
      - 'enhancement/**'