name: Feature Request
about: Suggest a new feature
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true