import mongoose from "mongoose";
import Parking from "./models/Parking.js";
import dotenv from "dotenv";
dotenv.config();


const rawData = [
  {
    name: "City Center Parking",
    location: "Sector 18, No_ida",
    pricePerHour: 40,
    status: "available",
    distance: "1km",
    capacity: 120,
    availableSlots: 45,
    isCovered: true,
    securityLevel: "high",
    rating: 4.5,
    openingTime: "08:00 AM",
    closingTime: "11:00 PM",
    floor: "Level 1",
    slotNumber: "A-12",
  },
  {
    name: "Metro Parking Space",
    location: "Rajiv Chowk, Delhi",
    pricePerHour: 30,
    status: "closed",
    distance: "3km",
    capacity: 200,
    availableSlots: 0,
    isCovered: false,
    securityLevel: "medium",
    rating: 4.0,
    openingTime: "06:00 AM",
    closingTime: "10:00 PM",
    floor: "Ground Floor",
    slotNumber: "B-07",
  },
  {
    name: "Mall Basement Parking",
    location: "Phoenix Mall, Mumbai",
    pricePerHour: 50,
    status: "available",
    distance: "5km",
    capacity: 350,
    availableSlots: 120,
    isCovered: true,
    securityLevel: "high",
    rating: 4.8,
    openingTime: "24 Hours",
    closingTime: "24 Hours",
    floor: "Basement 2",
    slotNumber: "C-34",
  },
  {
    name: "Central Park Parking",
    location: "Park Street, Kolkata",
    pricePerHour: 20,
    status: "available",
    distance: "10km",
    capacity: 90,
    availableSlots: 21,
    isCovered: false,
    securityLevel: "low",
    rating: 3.9,
    openingTime: "07:00 AM",
    closingTime: "09:00 PM",
    floor: "Ground Floor",
    slotNumber: "D-05",
  },
  {
    name: "Airport Multi-Level Parking",
    location: "IGI Airport, Delhi",
    pricePerHour: 80,
    status: "available",
    distance: "5km",
    capacity: 500,
    availableSlots: 210,
    isCovered: true,
    securityLevel: "high",
    rating: 4.7,
    openingTime: "24 Hours",
    closingTime: "24 Hours",
    floor: "Level 3",
    slotNumber: "E-21",
  },
  {
    name: "Tech Park Parking",
    location: "Electronic City, Bangalore",
    pricePerHour: 25,
    status: "closed",
    distance: "3km",
    capacity: 150,
    availableSlots: 0,
    isCovered: true,
    securityLevel: "medium",
    rating: 4.2,
    openingTime: "09:00 AM",
    closingTime: "08:00 PM",
    floor: "Level 1",
    slotNumber: "F-18",
  },
  {
    name: "Railway Station Parking",
    location: "Pune Junction, Pune",
    pricePerHour: 35,
    status: "available",
    distance: "1km",
    capacity: 250,
    availableSlots: 93,
    isCovered: false,
    securityLevel: "medium",
    rating: 4.1,
    openingTime: "24 Hours",
    closingTime: "24 Hours",
    floor: "Ground Floor",
    slotNumber: "G-02",
  },
  {
    name: "IT Hub Parking Lot",
    location: "Hinjewadi Phase 1, Pune",
    pricePerHour: 30,
    status: "available",
    distance: "10km",
    capacity: 300,
    availableSlots: 150,
    isCovered: true,
    securityLevel: "high",
    rating: 4.4,
    openingTime: "06:00 AM",
    closingTime: "12:00 AM",
    floor: "Level 2",
    slotNumber: "H-09",
  },
  {
    name: "Community Center Parking",
    location: "Rohini Sector 3, Delhi",
    pricePerHour: 15,
    status: "available",
    distance: "5km",
    capacity: 80,
    availableSlots: 32,
    isCovered: false,
    securityLevel: "low",
    rating: 3.5,
    openingTime: "08:00 AM",
    closingTime: "09:00 PM",
    floor: "Ground Floor",
    slotNumber: "I-14",
  },
  {
    name: "Techno Mall Parking",
    location: "Salt Lake, Kolkata",
    pricePerHour: 40,
    status: "available",
    distance: "3km",
    capacity: 220,
    availableSlots: 88,
    isCovered: true,
    securityLevel: "medium",
    rating: 4.3,
    openingTime: "10:00 AM",
    closingTime: "11:00 PM",
    floor: "Basement 1",
    slotNumber: "J-27",
  },
  {
    name: "Harbour View Parking",
    location: "Marine Drive, Mumbai",
    pricePerHour: 60,
    status: "closed",
    distance: "10km",
    capacity: 140,
    availableSlots: 0,
    isCovered: true,
    securityLevel: "high",
    rating: 4.6,
    openingTime: "07:00 AM",
    closingTime: "10:00 PM",
    floor: "Level 2",
    slotNumber: "K-03",
  },
  {
    name: "Stadium Parking Zone",
    location: "Chinnaswamy Stadium, Bangalore",
    pricePerHour: 50,
    status: "available",
    distance: "1km",
    capacity: 400,
    availableSlots: 178,
    isCovered: false,
    securityLevel: "medium",
    rating: 4.5,
    openingTime: "06:00 AM",
    closingTime: "11:00 PM",
    floor: "Ground Floor",
    slotNumber: "L-41",
  },
  {
    name: "City Mall Roof Parking",
    location: "Sector 62, No_ida",
    pricePerHour: 35,
    status: "available",
    distance: "5km",
    capacity: 260,
    availableSlots: 115,
    isCovered: false,
    securityLevel: "medium",
    rating: 4.0,
    openingTime: "09:00 AM",
    closingTime: "11:00 PM",
    floor: "Rooftop",
    slotNumber: "M-16",
  },
  {
    name: "Business Tower Parking",
    location: "Cyber Hub, Gurgaon",
    pricePerHour: 55,
    status: "available",
    distance: "3km",
    capacity: 180,
    availableSlots: 63,
    isCovered: true,
    securityLevel: "high",
    rating: 4.7,
    openingTime: "08:00 AM",
    closingTime: "10:00 PM",
    floor: "Level 4",
    slotNumber: "N-08",
  },
  {
    name: "Local Market Parking",
    location: "Lajpat Nagar, Delhi",
    pricePerHour: 20,
    status: "closed",
    distance: "1km",
    capacity: 110,
    availableSlots: 0,
    isCovered: false,
    securityLevel: "low",
    rating: 3.8,
    openingTime: "09:00 AM",
    closingTime: "09:00 PM",
    floor: "Ground Floor",
    slotNumber: "O-22",
  },
];

// Mongo URI
const MONGO_URI = process.env.MONGO_URI;
const parkingData = rawData.map((slot) => ({
  ...slot,
  _id: new mongoose.Types.ObjectId(),
}));
async function seedDB() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("MongoDB Connected");

    // Clear existing data (optional)
    await Parking.deleteMany();

    // Insert new data
    await Parking.insertMany(parkingData);

    console.log("Parking data inserted successfully!");
    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}

seedDB();
